-------------------------------------------------
--         Put your Lua functions here.        --
--                                             --
-- Note that you can also use external Scripts --
-------------------------------------------------
function ak.playercheck(who)
	ak[who] = ak[who] or ak.newplayer()
end

function ak.newplayer()
	return { 
		defs = {
		},
		bals = {
			["salve"] = true,
		},
		affs = {
			["addiction"]      = 0,
			["aeon"]           = 0,
			["agoraphobia"]    = 0,
			["anorexia"]       = 0,
			["aflame"]         = 0,
			["amnesia"]        = 0,
			["armexpend"]      = 0,
			["airfist"]        = 0,
			["asthma"]         = 0,
			["bitten"]         = 0,
			["blind"]          = 0,
			["blackout"]       = 0,
			["blisters"]       = 0,
			["bound"]          = 0,
			["brand"]          = 0,
			["claustrophobia"] = 0,
			["clumsiness"]     = 0,
			["conflagrate"]    = 0,
			["confusion"]      = 0,
			["corruption"]     = 0,
			["crippledarm"]    = 0,
			["crippledleg"]    = 0,
			["crushedthroat"]  = 0,
			["darkshade"]      = 0,
			["deadening"]      = 0,
			["deaf"]           = 0,
			["dementia"]       = 0,
			["depression"]     = 0,
			["dehydrate"]      = 0,
			["disloyalty"]     = 0,
			["disrupt"]        = 0,
			["dizziness"]      = 0,
			["enlighten"]      = 0,
			["epilepsy"]       = 0,
			["frozen"]         = 0,
			["generosity"]     = 0,
			["haemophilia"]    = 0,
			["hallucinations"] = 0,
			["hamstring"]      = 0,
			["hierophant"]     = 0,
			["healthleech"]    = 0,
			["hellsight"]      = 0,
			["hypersomnia"]    = 0,
			["hypochondria"]   = 0,
			["hypothermia"]    = 0,
			["impaleslash"]    = 0,
			["impatience"]     = 0,
			["inquisition"]    = 0,
			["insomnia"]       = 0,
			["justice"]        = 0,
			["kola"]           = 0,
			["latched"]        = 0,
			["lethargy"]       = 0,
			["lovers"]         = 0,
			["loneliness"]     = 0,
			["masochism"]      = 0,
			["manaleech"]      = 0,
			["mindclamp"]      = 0,
			["nausea"]         = 0,
			["pacifism"]       = 0,
			["paralysis"]      = 0,
			["parasite"]       = 0,
			["paranoia"]       = 0,
			["prone"]          = 0,
			["recklessness"]   = 0,
			["retribution"]    = 0,
			["rixil"]          = 0,
			["scalded"]        = 0,
			["scytherus"]      = 0,
			["selarnia"]       = 0,
			["sensitivity"]    = 0,
			["shadowmadness"]  = 0,
			["shyness"]        = 0,
			["slime"]          = 0,
			["slickness"]      = 0,
			["tempslickness"]  = 0,
			["sleep"]          = 0,
			["stupidity"]      = 0,
			["surge"]          = 0,
			["transfixed"]     = 0,
			["timeflux"]       = 0,
			["timeloop"]       = 0,
			["weariness"]      = 0,
			["wrenchhead"]     = 0,
			["wrenchtorso"]     = 0,
			["whisperingmadness"] = 0,
			["vertigo"]        = 0,
			["vitiate"]        = 0,
			["voidfist"]       = 0,
			["voyria"]         = 0,
			["airdisrupt"]     = 0,
			["earthdisrupt"]   = 0,
			["firedisrupt"]    = 0,
			["spiritdisrupt"]  = 0,
			["waterdisrupt"]   = 0,
			["rightleg"]       = 0,
			["leftleg"]       = 0,
			["rightarm"]       = 0,
			["leftarm"]       = 0,
			["head"]       = 0,
			["torso"]       = 0,
			["tension"]     = 0,
			["pressure"]    = 0,
			["unweavingbody"] = 0,
			["unweavingmind"] = 0,
			["unweavingspirit"] = 0,
		}
	}
end
