wsys.def = wsys.def or {}

wsys.tb = wsys.tb or {}
wsys.tb.defenceTable = {
  ["acrobatics"] = {["name"] = "Acrobatics", ["skillset"] = {"pranks", "swashbuckling"},},
  ["affinity"] = {["name"] = "Affinity", ["skillset"] = {"metamorphosis"}, ["manualcommand"] = "embrace spirit",},
  ["alertness"] = {["name"] = "Alertness", ["skillset"] = {"vision"},},
  ["aria"] = {["name"] = "Aria", ["skillset"] = {"voicecraft"},},
  ["arrowcatching"] = {["name"] = "Arrowcatching", ["skillset"] = {"pranks", "swashbuckling"},},
  ["astralform"] = {["name"] = "Astralform", ["skillset"] = {"occultism"},},
  ["astralvision"] = {["name"] = "Astralvision", ["skillset"] = {"occultism"}, ["manualcommand"] = "astralvision",},
  ["astronomy"] = {["name"] = "Astronomy", ["skillset"] = {"alchemy"},},
  ["balancing"] = {["name"] = "Balancing", ["skillset"] = {"pranks", "swashbuckling"},},
  ["barkskin"] = {["name"] = "Barkskin", ["skillset"] = {"sylvan", "woodlore"}, ["manualcommand"] = function() return wsys.manualbarkskin() end,},
  --["basking"] = {["name"] = "Basking", ["skillset"] = {"subterfuge"},},
  ["bedevilaura"] = {["name"] = "Bedevil Aura", ["skillset"] = {"healing"},},
  ["belltattoo"] = {["name"] = "Bell Tattoo", ["skillset"] = {"tattoos"}, ["manualcommand"] = "touch bell",},
  ["blackwind"] = {["name"] = "Blackwind", ["skillset"] = {"necromancy"},},
  ["blademastery"] = {["name"] = "Mastery", ["skillset"] = {"weaponmastery"},},
  ["blindness"] = {["name"] = "Blindness", ["skillset"] = {"curative"},},
  ["bodyblock"] = {["name"] = "Bodyblock", ["skillset"] = {"tekura"},},
  ["boostedregeneration"] = {["name"] = "Boosting", ["skillset"] = {"kaido"},},
  ["chargeshield"] = {["name"] = "Chargeshield", ["skillset"] = {"elementalism"},},
  ["clinging"] = {["name"] = "Clinging", ["skillset"] = {"survival"},},
  ["cloak"] = {["name"] = "Cloak", ["skillset"] = {"tattoos"},},
  ["coldresist"] = {["name"] = "Coldresist", ["skillset"] = {"enchantment"},},
  ["cohesion"] = {["name"] = "Cohesion", ["skillset"] = {"pervasion"},},
  ["consciousness"] = {["name"] = "Consciousness", ["skillset"] = {"kaido", "shindo"},},
  ["constitution"] = {["name"] = "Constitution", ["skillset"] = {"kaido", "striking"},},
  ["curseward"] = {["name"] = "Curseward", ["skillset"] = {"survival"},},
  ["deflect"] = {["name"] = "Deflect", ["skillset"] = {"weaponmastery"}, ["manualcommand"] = "deflect",},
  ["deafness"] = {["name"] = "Deafness", ["skillset"] = {"curative"},},
  ["deathaura"] = {["name"] = "Deathaura", ["skillset"] = {"necromancy"},},
  ["deathsight"] = {["name"] = "Deathsight", ["skillset"] = {"vision", "necromancy"}, ["manualcommand"] = function() return wsys.manualdeathsight() end,},
  ["demonarmour"] = {["name"] = "Demon armour", ["skillset"] = {"apostasy"},},
  --["demonfury"] = {["name"] = "Demon fury", ["skillset"] = {"apostasy"},},
  ["density"] = {["name"] = "Mass/Density", ["skillset"] = {"curative"},},
  ["devilmark"] = {["name"] = "Devilmark", ["skillset"] = {"occultism"},},
  ["diamondskin"] = {["name"] = "Diamondskin", ["skillset"] = {"magi"},},
  ["distortedaura"] = {["name"] = "Distortaura", ["skillset"] = {"occultism"},},
  ["dodging"] = {["name"] = "Dodging", ["skillset"] = {"shindo", "kaido"},},
  ["dragonarmour"] = {["name"] = "Dragonarmour", ["skillset"] = {"dragoncraft"},},
  ["dragonbreath"] = {["name"] = "Dragonbreath", ["skillset"] = {"dragoncraft"},},
  ["drunkensailor"] = {["name"] = "Drunkensailor", ["skillset"] = {"swashbuckling"},},
  ["earthshield"] = {["name"] = "Earthshield", ["skillset"] = {"healing"},},
  ["electricresist"] = {["name"] = "Electric resistance", ["skillset"] = {"enchantment"},},
  ["elusiveness"] = {["name"] = "Elusiveness", ["skillset"] = {"metamorphosis"}, ["manualcommand"] = "elusiveness on",},
  ["enduranceblessing"] = {["name"] = "Endurance", ["skillset"] = {"healing"},},
  --["eavesdropping"] = {["name"] = "Eavesdropping", ["skillset"] = {"subterfuge"},},
  ["evadeblock"] = {["name"] = "Evadeblock", ["skillset"] = {"tekura"},},
  ["evasion"] = {["name"] = "Evasion", ["skillset"] = {"metamorphosis"},},
  --["extispicy"] = {["name"] = "Extispicy", ["skillset"] = {"alchemy"},},
  ["extrusion"] = {["name"] = "Extrusion", ["skillset"] = {"sculpting"},},
  ["fangbarrier"] = {["name"] = "Sileris", ["skillset"] = {"curative"},},
  ["firefly"] = {["name"] = "Firefly", ["skillset"] = {"tattoos"}, ["manualcommand"] = "touch firefly",},
  ["fireresist"] = {["name"] = "fireresist", ["skillset"] = {"enchantment"},},
  ["fireshroud"] = {["name"] = "Fireshroud", ["skillset"] = {"ignition"},}, 
  ["firstaid"] = {["name"] = "Firstaid", ["skillset"] = {"woodlore"},},
  ["flailingstaff"] = {["name"] = "Flailingstaff", ["skillset"] = {"groves"},},
  ["fleetness"] = {["name"] = "Fleetness", ["skillset"] = {"woodlore"}, ["manualcommand"] = "fleetness",},
  --["frenzied"] = {["name"] = "Frenzy", ["skillset"] = {"necromancy"},},
  ["frostshield"] = {["name"] = "Frostshield", ["skillset"] = {"healing"},},
  ["fury"] = {["name"] = "Fury", ["skillset"] = {"chivalry"},},
  ["ghost"] = {["name"] = "Ghost", ["skillset"] = {"subterfuge"},},
  ["golgothagrace"] = {["name"] = "Golgotha", ["skillset"] = {"domination"},},
  ["gripping"] = {["name"] = "Gripping", ["skillset"] = {"chivalry", "twoarts", "puppetry", "vodun", "swashbuckling"},},
  ["groundwatch"] = {["name"] = "Groundwatch", ["skillset"] = {"vision"},},
  ["guidedstrike"] = {["name"] = "Guidedstrike", ["skillset"] = {"emulation"},},
  ["heartsfury"] = {["name"] = "HeartsFury", ["skillset"] = {"swashbuckling"},},
  ["harmony"] = {["name"] = "Harmony", ["skillset"] = {"druid"},},
  ["heldbreath"] = {["name"] = "Hold Breath", ["skillset"] = {"survival"},},
  ["heresy"] = {["name"] = "Heresy", ["skillset"] = {"spirituality"},},
  ["hiding"] = {["name"] = "Hiding", ["skillset"] = {"subterfuge", "woodlore"},},
  ["hypersense"] = {["name"] = "Hypersense", ["skillset"] = {"telepathy"},},
  ["hypersight"] = {["name"] = "Hypersight", ["skillset"] = {"vision"},},
  ["immunity"] = {["name"] = "Immunity", ["skillset"] = {"shindo", "kaido"},},
  ["indomitability"] = {["name"] = "Indomitability", ["skillset"] = {"emulation"},},
  ["insomnia"] = {["name"] = "Insomnia", ["skillset"] = {"survival"},},
  ["inspiration"] = {["name"] = "Inspiration", ["skillset"] = {"devotion"},},
  ["insulation"] = {["name"] = "Caloric", ["skillset"] = {"curative"},},
  ["kaiboost"] = {["name"] = "Kaiboost", ["skillset"] = {"kaido"},},
  ["kaitrance"] = {["name"] = "Kai trance", ["skillset"] = {"kaido"},},
  ["kola"] = {["name"] = "Kola", ["skillset"] = {"curative"},},
  ["lay"] = {["name"] = "Lay", ["skillset"] = {"voicecraft"},},
  ["levitating"] = {["name"] = "Levitating", ["skillset"] = {"curative"},},
  ["lifevision"] = {["name"] = "Lifevision", ["skillset"] = {"necromancy", "artefact"},},
  ["lifegiver"] = {["name"] = "Lifegiver", ["skillset"] = {"relic"},},
  ["lipreading"] = {["name"] = "Lipreading", ["skillset"] = {"subterfuge"},},
  ["magicresist"] = {["name"] = "Magic resistance", ["skillset"] = {"enchantment"},},
  ["mercury"] = {["name"] = "Mercury", ["skillset"] = {"alchemy"},},
  ["metawake"] = {["name"] = "Metawake", ["skillset"] = {"survival"},},
  ["mindcloak"] = {["name"] = "Mindcloak", ["skillset"] = {"telepathy"},},
  ["mindnet"] = {["name"] = "Mindnet", ["skillset"] = {"shindo","telepathy"},},
  ["mindseye"] = {["name"] = "Mindseye", ["skillset"] = {"tattoos"},},
  ["mindtelesense"] = {["name"] = "Mind Telesense", ["skillset"] = {"telepathy"},},
  ["mounted"] = {["name"] = "Mounted", ["skillset"] = {"riding"},},
  ["nightsight"] = {["name"] = "Nightsight", ["skillset"] = {"vision"},},
  --["numbness"] = {["name"] = "Numbness", ["skillset"] = {"kaido"},}, --apostasy Apathy maybe
  ["pacing"] = {["name"] = "Pacing", ["skillset"] = {"subterfuge"},},
  ["panacea"] = {["name"] = "Panacea", ["skillset"] = {"groves"},},
  ["phased"] = {["name"] = "Phase", ["skillset"] = {"subterfuge"}, ["manualcommand"] = "phase",},
  ["pinchblock"] = {["name"] = "Pinchblock", ["skillset"] = {"tekura"},},
  ["poisonresist"] = {["name"] = "Poison resistance", ["skillset"] = {"curative"},},
  --["prismatic"] = {["name"] = "Lyre", ["skillset"] = {"artefact"},},
  ["projectiles"] = {["name"] = "Projectiles", ["skillset"] = {"shindo", "kaido"},},
  ["putrefaction"] = {["name"] = "Putrefaction", ["skillset"] = {"necromancy"},},
  ["psicomprehend"] = {["name"] = "Comprehension", ["skillset"] = {"psionics"},},
  ["psitranscend"] = {["name"] = "Transcendence", ["skillset"] = {"psionics"},},
  ["rebounding"] = {["name"] = "Rebounding", ["skillset"] = {"curative"},},
  ["reflections"] = {["name"] = "Reflections", ["skillset"] = {"elementalism"},},
  --["reflexes"] = {["name"] = "Reflexes", ["skillset"] = {"metamorphosis"},},
  ["regeneration"] = {["name"] = "Regeneration", ["skillset"] = {"kaido"},},
  ["resistance"] = {["name"] = "Resistance", ["skillset"] = {"kaido", "chivalry", "metamorphosis"},},
  ["retaliation"] = {["name"] = "Retaliation", ["skillset"] = {"twoarts"},},
  ["scales"] = {["name"] = "Scales", ["skillset"] = {"subterfuge"},},
 -- ["scholasticism"] = {["name"] = "Myrrh", ["skillset"] = {"curative"}, ["manualcommand"] = wsys.manualmyrrh(),},
  ["secondsight"] = {["name"] = "Secondsight", ["skillset"] = {"subterfuge"},},
  ["secondskin"] = {["name"] = "Secondskin", ["skillset"] = {"weaving"},},
  ["selfishness"] = {["name"] = "Selfishness", ["skillset"] = {"survival"},},
  --["setweapon"] = {["name"] = "Impale", ["skillset"] = {"woodlore"},},
  ["shield"] = {["name"] = "Shield", ["skillset"] = {"tattoos"},},
  ["shinbinding"] = {["name"] = "Shinbinding", ["skillset"] = {"shindo"},},
  ["shinclarity"] = {["name"] = "Clarity", ["skillset"] = {"shindo"},},
  ["shintrance"] = {["name"] = "Shin Trance", ["skillset"] = {"shindo"},},
  ["shroud"] = {["name"] = "Shroud", ["skillset"] = {"occultism", "necromancy", "subterfuge", "artefact"},},
  ["skysight"] = {["name"] = "Skysight", ["skillset"] = {"duress"},},
  ["softfocusing"] = {["name"] = "Softfocus", ["skillset"] = {"vision"},},
  ["songbird"] = {["name"] = "Songbird", ["skillset"] = {"voicecraft"},},
  ["soulcage"] = {["name"] = "Soulcage", ["skillset"] = {"necromancy"},},
  ["slippery"] = {["name"] = "Slipperiness", ["skillset"] = {"pranks"},},
  ["speed"] = {["name"] = "Speed", ["skillset"] = {"curative"},},
  --["spinning"] = {["name"] = "Spinning", ["skillset"] = {"woodlore"},},
  --["spinningstaff"] = {["name"] = "Spinningstaff", ["skillset"] = {"groves"},},
  ["spiritbonded"] = {["name"] = "Spirit Bonding", ["skillset"] = {"metamorphosis"},  ["manualcommand"] = "bond spirit",},
  ["splitmind"] = {["name"] = "Splitmind", ["skillset"] = {"kaido"},},
  ["skywatch"] = {["name"] = "Skywatch", ["skillset"] = {"vision"},},
  ["standingfirm"] = {["name"] = "Sturdiness", ["skillset"] = {"kaido", "shindo", "chivalry"},},
  ["starburst"] = {["name"] = "Starburst", ["skillset"] = {"tattoos"}, ["manualcommand"] = "touch starburst",},
  ["stealth"] = {["name"] = "Stealth", ["skillset"] = {"metamorphosis"},},
  ["stonefist"] = {["name"] = "Stonefist", ["skillset"] = {"elementalism"},},
  ["stoneskin"] = {["name"] = "Stoneskin", ["skillset"] = {"magi"},},
  ["strata"] = {["name"] = "Strata", ["skillset"] = {"sculpting"},},
  ["sulphur"] = {["name"] = "Sulphur", ["skillset"] = {"alchemy"},},
  ["swiftcurse"] = {["name"] = "Swiftcurse", ["skillset"] = {"curses"},},
  ["telesense"] = {["name"] = "Telesense", ["skillset"] = {"vision"},},
  ["temperance"] = {["name"] = "Frost", ["skillset"] = {"curative"},},
  ["tempest"] = {["name"] = "Tempest", ["skillset"] = {"duress"},},
  ["tentacles"] = {["name"] = "Tentacles", ["skillset"] = {"occultism"},},
  ["thermalshield"] = {["name"] = "Thermalshield", ["skillset"] = {"healing"},},
  ["thirdeye"] = {["name"] = "Thirdeye", ["skillset"] = {"vision"},},
  ["tin"] = {["name"] = "Tin", ["skillset"] = {"alchemy"},},
  ["toughness"] = {["name"] = "Toughness", ["skillset"] = {"kaido", "shindo"},},
  ["treewatch"] = {["name"] = "Treewatch", ["skillset"] = {"vision"},},
  ["tremorsense"] = {["name"] = "Tremorsense", ["skillset"] = {"sculpting"},},
  ["truestare"] = {["name"] = "Truestare", ["skillset"] = {"evileye"},},
  ["tune"] = {["name"] = "Tune", ["skillset"] = {"voicecraft"},},
  ["vengeance"] = {["name"] = "Vengeance", ["skillset"] = {"necromancy"},},
  ["vigilance"] = {["name"] = "Vigilance", ["skillset"] = {"vision"},},
  ["vigour"] = {["name"] = "Vigour", ["skillset"] = {"groves"},},
  ["vitality"] = {["name"] = "Vitality", ["skillset"] = {"kaido", "metamorphosis"},},
  --["viridian"] = {["name"] = "Viridian", ["skillset"] = {"sylvan"},},
  ["waterwalking"] = {["name"] = "Waterwalking", ["skillset"] = {"shindo"},},
  ["weathering"] = {["name"] = "Weathering", ["skillset"] = {"chivalry","kaido","shindo",},},
  ["weaving"] = {["name"] = "Weaving", ["skillset"] = {"subterfuge"},},
  ["wildgrowth"] = {["name"] = "Wildgrowth", ["skillset"] = {"groves"},},
  ["willpowerblessing"] = {["name"] = "Willpower", ["skillset"] = {"healing"},},
-- Animal spirits for spiritform
  ["squirrel"] = {["name"] = "Squirrel", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("squirrel") end,},
  ["wildcat"] = {["name"] = "Wildcat", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("wildcat") end,},
  ["wolf"] = {["name"] = "Wolf", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("wolf") end,},
  ["turtle"] = {["name"] = "Turtle", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("turtle") end,},
  ["jackdaw"] = {["name"] = "Jackdaw", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("jackdaw") end,},
  ["cheetah"] = {["name"] = "Cheetah", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("cheetah") end,},
  ["owl"] = {["name"] = "Owl", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("owl") end,},
  ["hyena"] = {["name"] = "Hyena", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("hyena") end,},
  ["condor"] = {["name"] = "Condor", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("condor") end,},
  ["gopher"] = {["name"] = "Gopher", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("gopher") end,},
  ["sloth"] = {["name"] = "Sloth", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("sloth") end,},
  ["bear"] = {["name"] = "Bear", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("bear") end,},
  ["nightingale"] = {["name"] = "Nightingale", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("nightingale") end,},
  ["elephant"] = {["name"] = "Elephant", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("elephant") end,},
  ["wolverine"] = {["name"] = "Wolverine", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("wolverine") end,},
  ["jaguar"] = {["name"] = "Jaguar", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("jaguar") end,},
  ["icewyrm"] = {["name"] = "Icewyrm", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("icewyrm") end,},
  ["eagle"] = {["name"] = "Eagle", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("eagle") end,},
  ["gorilla"] = {["name"] = "Gorilla", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("gorilla") end,},
  ["basilisk"] = {["name"] = "Basilisk", ["skillset"] = {"spiritform"}, ["manualcommand"] = function() return wsys.metaform("basilisk") end,},
}

wsys.tb.defstripTable = {
  ["aura of rebounding defence"] = "rebounding",
  ["mastery of bladecraft"] = "blademastery",
  ["standing firm"] = "standingfirm",
  ["gripping"] = "gripping",
  ["resistance"] = "resistance",
  ["mercury"] = "mercury",
  ["sulphur"] = "sulphur",
  ["astronomy"] = "astronomy",
  ["tin"] = "tin",
  ["shroud"] = "shroud",
  ["demonic armour"] = "demonarmour",
  ["putrefaction"] = "putrefaction",
  ["lifevision"] = "lifevision",
  ["death aura"] = "deathaura",
  ["vengeance"] = "vengeance",
  ["truestare"] = "truestare",
  ["songbird"] = "songbird",
  ["balancing"] = "balancing",
  ["aria"] = "aria",
  ["Lay of distortion"] = "lay",
  ["tune"] = "tune",
  ["arrow catching"] = "arrowcatching",
  ["acrobatics"] = "acrobatics",
  ["Heart's Fury stance"] = "heartsfury",
  ["Drunken Sailor stance"] = "drunkensailor",
  ["mind net"] = "mindnet",
  ["Shin Clarity"] = "shinclarity",
  ["constitution"] = "constitution",
  ["waterwalking"] = "waterwalking",
  ["Shin Binding"] = "shinbinding",
  ["projectiles"] = "projectiles",
  ["consciousness"] = "consciousness",
  ["Shin Trance"] = "shintrance",
  ["dodging"] = "dodging",
  ["weathering"] = "weathering",
  ["toughness"] = "toughness",
  ["slippery"] = "slippery",
  ["diamondskin"] = "diamondskin",
  ["stoneskin"] = "stoneskin",
  ["reflections"] = "reflections",
  ["stonefist"] = "stonefist",
  ["chargeshield"] = "chargeshield",
  ["split mind"] = "split mind",
  ["pinchblock"] = "pinchblock",
  ["regeneration"] = "regeneration",
  ["hypersense"] = "hypersense",
  ["mindcloak"] = "mindcloak",
  ["kai boost"] = "kaiboost",
  ["mind telesense"] = "mindtelesense",
  ["evadeblock"] = "evadeblock",
  ["trance"] = "kaitrance",
  ["bodyblock"] = "bodyblock",
  ["distorted aura"] = "distortedaura",
  ["lifevision"] = "lifevision",
  ["devilmark"] = "devilmark",
  ["inspiration"] = "inspiration",
  ["earth Spiritshield"] = "earthshield",
  ["willpower"] = "willpowerblessing",
  ["bedevilaura"] = "bedevilaura",
  ["endurance"] = "enduranceblessing",
  ["frost Spiritshield"] = "frostshield",
  ["thermal Spiritshield"] = "thermalshield",
  ["firstaid"] = "firstaid",
  ["spirit bonding"] = "spiritbonded",
  ["stealth"] = "stealth",
  ["enhanced reflexes"] = "reflexes",
  ["affinity"] = "affinity",
  ["elusiveness"] = "elusiveness",
  ["ghost"] = "ghost",
  ["secondsight"] = "secondsight",
  ["weaving of the cobra"] = "weaving",
  ["hiding"] = "hiding",
  ["lipreading"] = "lipreading",
  ["scales of the serpent"] = "scales",
  ["pacing"] = "pacing",
  ["swiftcurse"] = "swiftcurse",
  ["barkskin"] = "barkskin",
  ["wild growth"] = "wildgrowth",
  ["harmony"] = "harmony",
  ["vigour"] = "vigour",
  ["metawake"] = "metawake",
  ["levitating"] = "levitating",
  ["deafness"] = "deafness",
  ["alertness"] = "alertness",
  ["groundwatch"] = "groundwatch",
  ["curseward"] = "curseward",
  ["nightsight"] = "nightsight",
  ["third eye"] = "thirdeye",
  ["soft focusing"] = "softfocusing",
  ["insulation"] = "insulation",
  ["selfishness"] = "selfishness",
  ["blindness"] = "blindness",
  ["density"] = "density",
  ["anti-weapon field"] = "rebounding",
  ["kola"] = "kola",
  ["belltattoo"] = "belltattoo",
  ["skywatch"] = "skywatch",
  ["hypersight"] = "hypersight",
  ["telesense"] = "telesense",
  ["vigilance"] = "vigilance",
  ["mindseye"] = "mindseye",
  ["temperance"] = "temperance",
  ["fire resistance"] = "fireresist",
  ["magic resistance"] = "magicresist",
  ["deathsight"] = "deathsight",
  ["electric resistance"] = "electricresist",
  ["treewatch"] = "treewatch",
  ["cloak"] = "cloak",
  ["insomnia"] = "insomnia",
  ["speed"] = "speed",
  ["venom"] = "poisonresist",
  ["clinging"] = "clinging",
  ["shield"] = "shield",
  --["scholasticism"] = " scholasticism",
  ["firefly"] = "firefly",
  ["held breath"] = "heldbreath",
}


