wsys.profile = "basic"
wsys.puppetmangle = false
wsys.waittime = .70
wsys.lifevision = false
wsys.vmode = false
wsys.absorbed = false
wsys.starbursted = false
wsys.mogged = false
wsys.affline = wsys.affline or 0
wsys.innewsroom = false
wsys.deletefull = false
