local room1 = mmp.roomEcho(multimatches[2][2])
local room2 = mmp.roomEcho(multimatches[2][3])
selectCurrentLine()
replace("")
mmp.echon("Stable wormhole between " .. room1)
mmp.roomEcho(room1)
echo(" and " .. room2)
mmp.roomEcho(room2)
echo(".\n")
